services:

  # Infrastructure
  goapp:
    image: golang:alpine
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "go run server.go -mode=server"
    depends_on:
      - postgres
      - redis
    ports:
      - ":8080"
    restart: on-failure
      
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/app/static
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - goapp

  npm:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "gulp"
    depends_on:
      - goapp

volumes:
  postgres-data:
  redis-data:
