services:

  # Infrastructure
  goapp:
    image: golang:alpine
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "go run server.go -mode=server"
    depends_on:
      - postgres
      - redis
    ports:
      - ":8080"
    restart: on-failure
    profiles: [production, development, staging]
      
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    profiles: [production, development, staging]

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    profiles: [production, development, staging]

  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/${APP_ENV}/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/app/static
      - ./private/ssl/${NGINX_HOST}:/etc/nginx/ssl

    ports:
      - "${NGINX_PORT}:80"
      - "${NGINX_SSL_PORT}:443"
    depends_on:
      - goapp
    profiles: [production, development, staging]

  npm:
    build:
      context: .
      dockerfile: docker/npm/Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "gulp"
    depends_on:
      - goapp
    restart: on-failure
    profiles: [development]

volumes:
  postgres-data:
  redis-data:
